### ISSUE TITLE
'SyntaxError: Unexpected token {' when running with node 4 and node 5

### ISSUE THREAD

**Issue by GabLeRoux** [abraham/pkg-ok#6]
Hi there, I recently updated a project and when running `pkg-ok`, it seems to fail on the following versions:

* pkg-ok 2.2.0

```bash
$ node --version
v4.9.1
$ npm --version
2.15.11
$ nvm --version
0.33.11
11.49s$ npm install 
```

How it's failing on my side:

```
husky
CI detected, skipping Git hooks installation
> cisco-password-decoder@1.0.2 prepublish /Users/travis/build/GabLeRoux/cisco-password-decoder-cli
> pkg-ok
/Users/travis/build/GabLeRoux/cisco-password-decoder-cli/node_modules/pkg-ok/index.js:86
function pkgOk (dir, { fields = [], bin = [] } = {}) {
                     ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/travis/build/GabLeRoux/cisco-password-decoder-cli/node_modules/pkg-ok/bin.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/travis/.nvm/versions/node/v4.9.1/bin/node" "/Users/travis/.nvm/versions/node/v4.9.1/bin/npm" "install"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! cisco-password-decoder@1.0.2 prepublish: `pkg-ok`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cisco-password-decoder@1.0.2 prepublish script 'pkg-ok'.
npm ERR! This is most likely a problem with the cisco-password-decoder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pkg-ok
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cisco-password-decoder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cisco-password-decoder
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/travis/build/GabLeRoux/cisco-password-decoder-cli/npm-debug.log
```

https://travis-ci.org/GabLeRoux/cisco-password-decoder-cli/jobs/378766686

Note: I'm ok with it as I personally don't really care about node 4 or node 5. I'm not even sure if it's exactly a problem with `pkg-ok`, but I see your [travis build](https://travis-ci.org/typicode/pkg-ok) only seem to run against `v10.0.0` and Node 6.

For now, I'll simply disable node 4 and node 5 on my side ;)
Thanks for this nice package 👍

**Comment by typicode** [comment]
Hey @GabLeRoux 

Sorry for the confusion.
Thanks for the feedback, glad you like it :)

You're correct, it was changed in v2.0.0. I've just updated the CHANGELOG to mention that for ` pkg-ok v2.0.0`
https://github.com/typicode/pkg-ok/blob/master/CHANGELOG.md#200

**Comment by typicode** [comment]
I think they're not supporting Node 4 since April as well (but there may be always cases where you may need to support old versions I guess)
